-- ============================================================
-- AGENTY: Missions Table — "The Mission Factory"
-- Dynamic missions generated by the Mission Architect AI.
-- Parent creates via Command Deck; kid plays via /bridge/lab.
-- Security: Parent manages own rows, anyone reads active missions.
-- ============================================================

create table public.missions (
  id                uuid primary key default gen_random_uuid(),
  slug              text unique not null,
  title             text not null,
  template_id       text not null,             -- references TemplateManifest.templateId (app-level)
  status            text not null default 'draft'
                    check (status in ('draft', 'active', 'archived')),
  accent_color      text not null default '#3B82F6',
  is_critical       boolean not null default false,
  default_objective text not null,
  description       text not null,
  stats             jsonb not null,            -- MissionStatConfig[] array
  xp_reward         int not null default 150   check (xp_reward >= 0 and xp_reward <= 1000),
  gold_reward       int not null default 75    check (gold_reward >= 0 and gold_reward <= 500),
  grade_level       int not null default 4     check (grade_level >= 1 and grade_level <= 8),
  topic             text not null,
  skill_focus       text not null default 'multiplication',
  created_by        uuid not null references auth.users(id) on delete cascade,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

comment on table public.missions is 'AI-generated missions — parent creates, kid plays.';

-- Auto-update timestamp (reuses existing trigger function from core tables)
create trigger missions_updated_at
  before update on public.missions
  for each row execute function public.handle_updated_at();

-- Indexes
create index idx_missions_created_by on public.missions(created_by);
create index idx_missions_status on public.missions(status);
create index idx_missions_slug on public.missions(slug);

-- ═══════════════════════════════════
-- Row-Level Security
-- ═══════════════════════════════════
alter table public.missions enable row level security;

-- Parent can manage their own missions (CRUD)
create policy "Parents can view own missions"
  on public.missions for select
  using (auth.uid() = created_by);

create policy "Parents can insert own missions"
  on public.missions for insert
  with check (auth.uid() = created_by);

create policy "Parents can update own missions"
  on public.missions for update
  using (auth.uid() = created_by)
  with check (auth.uid() = created_by);

create policy "Parents can delete own missions"
  on public.missions for delete
  using (auth.uid() = created_by);

-- Anyone authenticated can view active missions (kid plays these)
create policy "Anyone can view active missions"
  on public.missions for select
  using (status = 'active');
